$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: conda-in-dockerfile
endpoint_name: donut-rvlcdip
model: 
  name: minimal-cc-model 
  path: ../asset/model
code_configuration: 
  code: ../asset/onlinescoring
  scoring_script: score.py
environment:  
  name: conda-in-dockerfile
  image: crazureai.azurecr.io/azure-ai-experiments/azure-donut-base-finetuned-rvlcdip:1
  inference_config:
    liveness_route:
      path: /
      port: 5001
    readiness_route:
      path: /
      port: 5001
    scoring_route:
      path: /score
      port: 5001
instance_type: Standard_DS4_v2
instance_count: 1
request_settings:
  request_timeout_ms: 60000